using Microsoft.Data.Sqlite;using Microsoft.EntityFrameworkCore;using OpenDentalFlow.Api.Data;using OpenDentalFlow.Api.Domain;using OpenDentalFlow.Api.Services;
namespace OpenDentalFlow.Tests;
public class CoreTests {
 [Fact] public void Access_tokens_are_unique_and_high_entropy(){var s=new CodeService();var values=Enumerable.Range(0,1000).Select(_=>s.Token()).ToArray();Assert.Equal(1000,values.Distinct().Count());Assert.All(values,x=>Assert.Equal(20,x.Length));}
 [Fact] public async Task Database_rejects_duplicate_patient_sequence(){await using var connection=new SqliteConnection("DataSource=:memory:");await connection.OpenAsync();var options=new DbContextOptionsBuilder<AppDbContext>().UseSqlite(connection).Options;await using var db=new AppDbContext(options);await db.Database.EnsureCreatedAsync();var c=new Clinic{Name="Test",ShortCode="TST"};db.Add(c);await db.SaveChangesAsync();db.Patients.AddRange(new(){ClinicId=c.Id,PatientCode="TST-001",ClinicSequence=1,FirstName="A",LastName="B"},new(){ClinicId=c.Id,PatientCode="TST-002",ClinicSequence=1,FirstName="C",LastName="D"});await Assert.ThrowsAsync<DbUpdateException>(()=>db.SaveChangesAsync());}
 [Fact] public async Task Short_code_suggestions_are_usable_and_unique(){var options=new DbContextOptionsBuilder<AppDbContext>().UseSqlite("DataSource=:memory:").Options;await using var db=new AppDbContext(options);await db.Database.OpenConnectionAsync();await db.Database.EnsureCreatedAsync();db.Clinics.Add(new(){Name="Dental Park",ShortCode="DEN"});await db.SaveChangesAsync();var result=await new ShortCodeService(db).SuggestAsync("Dent Art");Assert.NotEmpty(result);Assert.All(result,x=>Assert.Matches("^[A-Z0-9]{3,4}$",x));Assert.DoesNotContain("DEN",result);}
 [Fact] public void Job_workflow_has_only_lab_and_dispatched_states(){Assert.Equal(new[]{"InLab","Dispatched"},Enum.GetNames<JobStatus>());}
 [Fact] public async Task Database_rejects_duplicate_usernames(){await using var connection=new SqliteConnection("DataSource=:memory:");await connection.OpenAsync();var options=new DbContextOptionsBuilder<AppDbContext>().UseSqlite(connection).Options;await using var db=new AppDbContext(options);await db.Database.EnsureCreatedAsync();db.Users.AddRange(new(){Username="worker",PasswordHash="x"},new(){Username="worker",PasswordHash="y"});await Assert.ThrowsAsync<DbUpdateException>(()=>db.SaveChangesAsync());}
}
