using System.ComponentModel.DataAnnotations;

namespace OpenDentalFlow.Api.Domain;

public enum UserRole { Admin, Employee, Viewer }
public enum JobStatus { InLab, Dispatched }
public enum PhotoCategory { Intraoral, Shade, Impression, Model, TryIn, Design, Production, Finished, Revision, ClinicNote, Other }

public class User { public int Id { get; set; } [MaxLength(50)] public string Username { get; set; } = ""; public string PasswordHash { get; set; } = ""; public UserRole Role { get; set; } public bool IsActive { get; set; } = true; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class Clinic { public int Id { get; set; } [MaxLength(150)] public string Name { get; set; } = ""; [MaxLength(4)] public string ShortCode { get; set; } = ""; public string? Phone { get; set; } public string? Address { get; set; } public string? Notes { get; set; } public bool IsActive { get; set; } = true; public int LastPatientSequence { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public List<Patient> Patients { get; set; } = []; }
public class Patient { public int Id { get; set; } public string PatientCode { get; set; } = ""; public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public int ClinicId { get; set; } public Clinic Clinic { get; set; } = null!; public int ClinicSequence { get; set; } public string? Description { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public bool IsActive { get; set; } = true; public List<Job> Jobs { get; set; } = []; }
public class Job { public int Id { get; set; } public string JobCode { get; set; } = ""; public int PatientId { get; set; } public Patient Patient { get; set; } = null!; public int ClinicId { get; set; } public Clinic Clinic { get; set; } = null!; public int JobSequence { get; set; } public DateTime? DueDate { get; set; } public string JobType { get; set; } = ""; public string? Material { get; set; } public string? Shade { get; set; } public string Teeth { get; set; } = ""; public int UnitCount { get; set; } public bool DigitalModelRequired { get; set; } public string Priority { get; set; } = "Normal"; public JobStatus Status { get; set; } = JobStatus.InLab; public string? Description { get; set; } public string AccessToken { get; set; } = ""; public bool AccessEnabled { get; set; } = true; public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; public DateTime? CompletedAt { get; set; } public List<JobStatusHistory> StatusHistory { get; set; } = []; public List<JobPhoto> Photos { get; set; } = []; public List<JobNote> Notes { get; set; } = []; public List<JobActivity> Activities { get; set; } = []; }
public class JobActivity { public int Id { get; set; } public int JobId { get; set; } public Job Job { get; set; } = null!; public string StepType { get; set; } = ""; public string? Description { get; set; } public int? CreatedByUserId { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class JobStatusHistory { public int Id { get; set; } public int JobId { get; set; } public Job Job { get; set; } = null!; public JobStatus OldStatus { get; set; } public JobStatus NewStatus { get; set; } public int? ChangedByUserId { get; set; } public DateTime ChangedAt { get; set; } = DateTime.UtcNow; }
public class JobPhoto { public int Id { get; set; } public int JobId { get; set; } public Job Job { get; set; } = null!; public PhotoCategory Category { get; set; } public string OriginalFileName { get; set; } = ""; public string StoredFileName { get; set; } = ""; public string? ThumbnailStoredFileName { get; set; } public string MimeType { get; set; } = ""; public long FileSize { get; set; } public int? UploadedByUserId { get; set; } public bool UploadedViaQr { get; set; } public DateTime UploadedAt { get; set; } = DateTime.UtcNow; }
public class JobNote { public int Id { get; set; } public int JobId { get; set; } public Job Job { get; set; } = null!; public string Text { get; set; } = ""; public int? CreatedByUserId { get; set; } public bool CreatedViaQr { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class SystemSetting { public int Id { get; set; } public string Key { get; set; } = ""; public string Value { get; set; } = ""; }
public class JobTypeDefinition { public int Id { get; set; } public string Name { get; set; } = ""; public string? DefaultMaterial { get; set; } public bool IsActive { get; set; } = true; public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
public class MaterialDefinition { public int Id { get; set; } public string Name { get; set; } = ""; public bool IsActive { get; set; } = true; public int SortOrder { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
