using System.Security.Cryptography; using System.Text.RegularExpressions; using BarcodeStandard; using SkiaSharp; using Microsoft.EntityFrameworkCore; using OpenDentalFlow.Api.Data; using OpenDentalFlow.Api.Domain; using QRCoder;
namespace OpenDentalFlow.Api.Services;
public interface IShortCodeService { Task<List<string>> SuggestAsync(string name); }
public class ShortCodeService(AppDbContext db):IShortCodeService { public async Task<List<string>> SuggestAsync(string name){var map=new Dictionary<char,char>{{'İ','I'},{'Ş','S'},{'Ğ','G'},{'Ü','U'},{'Ö','O'},{'Ç','C'}};var s=new string(name.ToUpperInvariant().Select(ch=>map.GetValueOrDefault(ch,ch)).ToArray());var words=Regex.Matches(s,"[A-Z0-9]+").Select(x=>x.Value).ToArray();var joined=string.Concat(words);if(joined.Length==0)joined="KLN";var c=new List<string>();if(words.Length>1)c.Add(string.Concat(words.Select(x=>x[0])).PadRight(3,joined[^1])[..3]);c.Add(joined.PadRight(3,'X')[..3]);c.Add($"{joined[0]}{joined[joined.Length/2]}{joined[^1]}");for(var i=1;i<10;i++)c.Add(($"{joined[..Math.Min(3,joined.Length)]}{i}").PadRight(3,'X')[..Math.Min(4,Math.Max(3,joined.Length+1))]);var used=await db.Clinics.Select(x=>x.ShortCode).ToListAsync();return c.Where(x=>x.Length is 3 or 4&&!used.Contains(x)).Distinct().Take(5).ToList();} }
public interface ICodeService { string Token(); } public class CodeService:ICodeService { public string Token()=>Convert.ToHexString(RandomNumberGenerator.GetBytes(10)); }
public interface ILabelService { byte[] Qr(string url); byte[] Barcode(string value); }
public class LabelService:ILabelService { public byte[] Qr(string url){using var d=QRCodeGenerator.GenerateQrCode(url,QRCodeGenerator.ECCLevel.Q);return new PngByteQRCode(d).GetGraphic(8);}public byte[] Barcode(string value){var b=new Barcode();using var image=b.Encode(BarcodeStandard.Type.Code128,value,SKColors.Black,SKColors.White,360,80);using var data=image.Encode(SKEncodedImageFormat.Png,100);return data.ToArray();} }
public interface IFileStorage { Task<JobPhoto> SaveAsync(int jobId,IFormFile file,PhotoCategory category,bool viaQr,int? userId); }
public class LocalFileStorage(IWebHostEnvironment env,AppDbContext db,IConfiguration cfg):IFileStorage { public async Task<JobPhoto> SaveAsync(int jobId,IFormFile file,PhotoCategory category,bool viaQr,int? userId){var allowed=new Dictionary<string,string>{{"image/jpeg",".jpg"},{"image/png",".png"},{"image/webp",".webp"}};if(!allowed.TryGetValue(file.ContentType.ToLowerInvariant(),out var ext))throw new InvalidOperationException(file.ContentType.Contains("heic",StringComparison.OrdinalIgnoreCase)?"HEIC desteklenmiyor. JPEG, PNG veya WebP kullanın.":"Desteklenmeyen dosya türü.");var max=cfg.GetValue<long>("Uploads:MaxBytes",10485760);if(file.Length<=0||file.Length>max)throw new InvalidOperationException($"Dosya en fazla {max/1048576} MB olabilir.");var dir=Path.Combine(env.ContentRootPath,"uploads",jobId.ToString());Directory.CreateDirectory(dir);var stored=$"{Guid.NewGuid():N}{ext}";await using(var fs=File.Create(Path.Combine(dir,stored)))await file.CopyToAsync(fs);var p=new JobPhoto{JobId=jobId,Category=category,OriginalFileName=Path.GetFileName(file.FileName),StoredFileName=$"{jobId}/{stored}",MimeType=file.ContentType,FileSize=file.Length,UploadedViaQr=viaQr,UploadedByUserId=userId};db.JobPhotos.Add(p);await db.SaveChangesAsync();return p;} }
