using System.IdentityModel.Tokens.Jwt; using System.Security.Claims; using System.Text; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using Microsoft.IdentityModel.Tokens; using OpenDentalFlow.Api.Contracts; using OpenDentalFlow.Api.Data; using OpenDentalFlow.Api.Domain; using OpenDentalFlow.Api.Services;
namespace OpenDentalFlow.Api.Controllers;

[ApiController,Route("api/auth")] public class AuthController(AppDbContext db,IConfiguration cfg):ControllerBase { [HttpPost("login"),AllowAnonymous] public async Task<IActionResult> Login(LoginDto dto){var u=await db.Users.SingleOrDefaultAsync(x=>x.Username==dto.Username&&x.IsActive); if(u is null||!BCrypt.Net.BCrypt.Verify(dto.Password,u.PasswordHash))return Unauthorized(new{message="Kullanıcı adı veya parola hatalı."}); var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(cfg["Jwt:Key"]!)); var token=new JwtSecurityToken(claims:[new(ClaimTypes.NameIdentifier,u.Id.ToString()),new(ClaimTypes.Name,u.Username),new(ClaimTypes.Role,u.Role.ToString())],expires:DateTime.UtcNow.AddHours(12),signingCredentials:new(key,SecurityAlgorithms.HmacSha256));return Ok(new{token=new JwtSecurityTokenHandler().WriteToken(token),u.Username,role=u.Role.ToString()});} }

[ApiController,Route("api/clinics"),Authorize] public class ClinicsController(AppDbContext db,IShortCodeService codes):ControllerBase { [HttpGet] public Task<List<Clinic>> Get()=>db.Clinics.OrderBy(x=>x.Name).ToListAsync(); [HttpGet("suggestions")] public Task<List<string>> Suggestions([FromQuery]string name)=>codes.SuggestAsync(name); [HttpPost,Authorize(Roles="Admin,Employee")] public async Task<IActionResult> Create(ClinicDto d){var shortCode=string.IsNullOrWhiteSpace(d.ShortCode)?(await codes.SuggestAsync(d.Name)).FirstOrDefault():d.ShortCode.Trim().ToUpperInvariant();if(string.IsNullOrWhiteSpace(shortCode)||!System.Text.RegularExpressions.Regex.IsMatch(shortCode,"^[A-Z0-9]{3,4}$"))return BadRequest(new{message="Kısa kod 3 veya 4 büyük harf/rakam olmalıdır. Örnek: DPL."});var x=new Clinic{Name=d.Name.Trim(),ShortCode=shortCode,Phone=d.Phone?.Trim(),Address=d.Address?.Trim(),Notes=d.Notes?.Trim(),IsActive=d.IsActive};db.Add(x);try{await db.SaveChangesAsync();}catch(DbUpdateException){return Conflict(new{message="Klinik kısa kodu kullanımda. Önerilerden başka bir kod seçin."});}return CreatedAtAction(nameof(Get),new{id=x.Id},x);} [HttpPut("{id:int}"),Authorize(Roles="Admin,Employee")] public async Task<IActionResult> Update(int id,ClinicDto d){var x=await db.Clinics.FindAsync(id);if(x is null)return NotFound();x.Name=d.Name;x.ShortCode=(d.ShortCode??x.ShortCode).ToUpperInvariant();x.Phone=d.Phone;x.Address=d.Address;x.Notes=d.Notes;x.IsActive=d.IsActive;await db.SaveChangesAsync();return Ok(x);} }

[ApiController,Route("api/patients"),Authorize] public class PatientsController(AppDbContext db):ControllerBase { [HttpGet] public async Task<IActionResult> Get([FromQuery]string? q){var x=db.Patients.Include(p=>p.Clinic).AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(q))x=x.Where(p=>p.PatientCode.Contains(q)||p.FirstName.Contains(q)||p.LastName.Contains(q)||p.Clinic.Name.Contains(q));return Ok(await x.OrderByDescending(p=>p.CreatedAt).Take(100).ToListAsync());} [HttpGet("matches")]public async Task<IActionResult> Matches([FromQuery]int clinicId,[FromQuery]string firstName,[FromQuery]string lastName){var first=firstName.Trim().ToLower();var last=lastName.Trim().ToLower();return Ok(await db.Patients.AsNoTracking().Where(p=>p.ClinicId==clinicId&&p.IsActive&&p.FirstName.ToLower()==first&&p.LastName.ToLower()==last).Select(p=>new{p.Id,p.PatientCode,p.FirstName,p.LastName,JobCount=p.Jobs.Count,LastJobAt=p.Jobs.Max(j=>(DateTime?)j.CreatedAt)}).ToListAsync());} [HttpGet("{id:int}")]public async Task<IActionResult> One(int id){var x=await db.Patients.AsNoTracking().Include(p=>p.Clinic).Include(p=>p.Jobs.OrderByDescending(j=>j.CreatedAt)).ThenInclude(j=>j.Activities.OrderByDescending(a=>a.CreatedAt)).SingleOrDefaultAsync(p=>p.Id==id);return x is null?NotFound():Ok(x);} }

[ApiController,Route("api/jobs"),Authorize] public class JobsController(AppDbContext db,ICodeService codes,IFileStorage storage,IConfiguration cfg,ILabelService labels,IWindowsPrinterService printers):ControllerBase {
 IQueryable<Job> Full()=>db.Jobs.Include(x=>x.Patient).Include(x=>x.Clinic).Include(x=>x.Photos).Include(x=>x.Notes).Include(x=>x.StatusHistory).Include(x=>x.Activities);
 [HttpGet] public async Task<IActionResult> Get([FromQuery]string? q,[FromQuery]JobStatus? status,[FromQuery]int page=1,[FromQuery]int pageSize=50){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,200);var x=Full().AsNoTracking();if(status.HasValue)x=x.Where(j=>j.Status==status);if(!string.IsNullOrWhiteSpace(q))x=x.Where(j=>j.JobCode.Contains(q)||j.Patient.PatientCode.Contains(q)||j.Patient.FirstName.Contains(q)||j.Patient.LastName.Contains(q)||j.Clinic.Name.Contains(q)||j.Clinic.ShortCode.Contains(q));var total=await x.CountAsync();Response.Headers.Append("X-Total-Count",total.ToString());Response.Headers.Append("X-Page",page.ToString());Response.Headers.Append("X-Page-Size",pageSize.ToString());return Ok(await x.OrderByDescending(j=>j.CreatedAt).Skip((page-1)*pageSize).Take(pageSize).ToListAsync());}
 [HttpGet("{id:int}")]public async Task<IActionResult> One(int id){var x=await Full().SingleOrDefaultAsync(j=>j.Id==id);return x is null?NotFound():Ok(x);} [HttpGet("code/{jobCode}")]public async Task<IActionResult> ByCode(string jobCode){var x=await Full().SingleOrDefaultAsync(j=>j.JobCode==jobCode);return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Roles="Admin,Employee")] public async Task<IActionResult> Create(CreateJobDto d){if(d.Teeth.Any(t=>t is <11 or >48))return BadRequest(new{message="Geçersiz FDI diş numarası."}); await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);var clinic=await db.Clinics.SingleOrDefaultAsync(x=>x.Id==d.ClinicId&&x.IsActive);if(clinic is null)return BadRequest(new{message="Aktif klinik seçin."});Patient? p=d.PatientId is null?null:await db.Patients.SingleOrDefaultAsync(x=>x.Id==d.PatientId&&x.ClinicId==d.ClinicId);if(p is null){if(string.IsNullOrWhiteSpace(d.FirstName)||string.IsNullOrWhiteSpace(d.LastName))return BadRequest(new{message="Yeni hasta için ad ve soyad zorunludur."});clinic.LastPatientSequence++;p=new Patient{Clinic=clinic,ClinicSequence=clinic.LastPatientSequence,PatientCode=$"{clinic.ShortCode}-{clinic.LastPatientSequence:000}",FirstName=d.FirstName.Trim(),LastName=d.LastName.Trim(),Description=d.PatientDescription};db.Patients.Add(p);await db.SaveChangesAsync();}var seq=await db.Jobs.Where(x=>x.PatientId==p.Id).MaxAsync(x=>(int?)x.JobSequence)??0;seq++;var j=new Job{Patient=p,Clinic=clinic,JobSequence=seq,JobCode=$"{p.PatientCode}-{seq}",DueDate=d.DueDate,JobType=d.JobType,Material=d.Material,Shade=d.Shade,Teeth=string.Join(',',d.Teeth.Distinct().Order()),UnitCount=d.UnitCount??d.Teeth.Distinct().Count(),DigitalModelRequired=d.DigitalModelRequired,Priority=d.Priority,Description=d.Description,AccessToken=codes.Token()};db.Jobs.Add(j);db.JobStatusHistory.Add(new(){Job=j,OldStatus=JobStatus.InLab,NewStatus=JobStatus.InLab});try{await db.SaveChangesAsync();await tx.CommitAsync();}catch(DbUpdateException){await tx.RollbackAsync();return Conflict(new{message="Eş zamanlı kod üretimi çakıştı; yeniden deneyin."});}return CreatedAtAction(nameof(One),new{id=j.Id},new{j.Id,j.JobCode,j.AccessToken});}
 [HttpPatch("{id:int}/status"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult> Status(int id,StatusDto d){var j=await db.Jobs.FindAsync(id);if(j is null)return NotFound();var old=j.Status;if(old==d.Status)return Ok(j);j.Status=d.Status;j.UpdatedAt=DateTime.UtcNow;j.CompletedAt=d.Status==JobStatus.Dispatched?DateTime.UtcNow:null;db.JobStatusHistory.Add(new(){JobId=id,OldStatus=old,NewStatus=d.Status,ChangedByUserId=UserId()});await db.SaveChangesAsync();return Ok(j);}
 [HttpPost("{id:int}/notes"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult> Note(int id,NoteDto d){if(!await db.Jobs.AnyAsync(x=>x.Id==id))return NotFound();var n=new JobNote{JobId=id,Text=d.Text,CreatedByUserId=UserId()};db.Add(n);await db.SaveChangesAsync();return Ok(n);} [HttpPost("{id:int}/activities"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult> Activity(int id,ActivityDto d){var j=await db.Jobs.FindAsync(id);if(j is null)return NotFound();var a=new JobActivity{JobId=id,StepType=d.StepType.Trim(),Description=d.Description?.Trim(),CreatedByUserId=UserId()};j.UpdatedAt=DateTime.UtcNow;db.Add(a);await db.SaveChangesAsync();return Ok(a);} [HttpPost("{id:int}/photos"),Authorize(Roles="Admin,Employee"),RequestSizeLimit(52428800)]public async Task<IActionResult> Photos(int id,[FromForm]List<IFormFile> files,[FromForm]PhotoCategory category=PhotoCategory.Other){if(!await db.Jobs.AnyAsync(x=>x.Id==id))return NotFound();var result=new List<JobPhoto>();foreach(var f in files)result.Add(await storage.SaveAsync(id,f,category,false,UserId()));return Ok(result);}
 [HttpPost("{id:int}/regenerate-access-token"),Authorize(Roles="Admin")]public async Task<IActionResult> Regen(int id){var j=await db.Jobs.FindAsync(id);if(j is null)return NotFound();j.AccessToken=codes.Token();j.AccessEnabled=true;await db.SaveChangesAsync();return Ok(new{j.AccessToken});}
 [HttpPatch("{id:int}/access"),Authorize(Roles="Admin")]public async Task<IActionResult>Access(int id,AccessDto d){var j=await db.Jobs.FindAsync(id);if(j is null)return NotFound();j.AccessEnabled=d.Enabled;j.UpdatedAt=DateTime.UtcNow;await db.SaveChangesAsync();return Ok(new{j.AccessEnabled});}
 [HttpGet("{id:int}/label")]public async Task<IActionResult> Label(int id){var j=await Full().SingleOrDefaultAsync(x=>x.Id==id);if(j is null)return NotFound();var baseUrl=(await db.SystemSettings.SingleOrDefaultAsync(x=>x.Key=="PublicBaseUrl"))?.Value??cfg["PublicBaseUrl"];var url=$"{baseUrl}/j/{j.AccessToken}";var qrData="data:image/png;base64,"+Convert.ToBase64String(labels.Qr(url));var barcodeData="data:image/png;base64,"+Convert.ToBase64String(labels.Barcode(j.JobCode));return Ok(new{job=j,publicUrl=url,qrData,barcodeData});} [HttpPost("{id:int}/print"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult> Print(int id){var j=await Full().SingleOrDefaultAsync(x=>x.Id==id);if(j is null)return NotFound();var printer=(await db.SystemSettings.SingleOrDefaultAsync(x=>x.Key=="DefaultPrinter"))?.Value;var baseUrl=(await db.SystemSettings.SingleOrDefaultAsync(x=>x.Key=="PublicBaseUrl"))?.Value??cfg["PublicBaseUrl"];try{printers.PrintLabel(j,$"{baseUrl}/j/{j.AccessToken}",printer??"");return Ok(new{message="Etiket yazıcıya gönderildi.",printer});}catch(Exception ex){return BadRequest(new{message=ex.Message});}} [HttpGet("{id:int}/label/qr")]public async Task<IActionResult> Qr(int id){var j=await db.Jobs.FindAsync(id);return j is null?NotFound():File(labels.Qr($"{cfg["PublicBaseUrl"]}/j/{j.AccessToken}"),"image/png");}[HttpGet("{id:int}/label/barcode")]public async Task<IActionResult> Barcode(int id){var j=await db.Jobs.FindAsync(id);return j is null?NotFound():File(labels.Barcode(j.JobCode),"image/png");} int? UserId()=>int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:null;
}

[ApiController,Route("api/public/jobs"),AllowAnonymous] public class PublicJobsController(AppDbContext db,IFileStorage storage):ControllerBase { async Task<Job?> Find(string token)=>await db.Jobs.Include(x=>x.Patient).Include(x=>x.Clinic).Include(x=>x.Photos).Include(x=>x.Notes).SingleOrDefaultAsync(x=>x.AccessToken==token&&x.AccessEnabled); [HttpGet("{token}")]public async Task<IActionResult> Get(string token){var j=await Find(token);return j is null?NotFound(new{message="Bağlantı geçersiz veya iptal edilmiş."}):Ok(j);} [HttpPost("{token}/notes")]public async Task<IActionResult> Note(string token,NoteDto d){var j=await Find(token);if(j is null)return NotFound();var n=new JobNote{JobId=j.Id,Text=d.Text,CreatedViaQr=true};db.Add(n);await db.SaveChangesAsync();return Ok(n);} [HttpPost("{token}/photos"),RequestSizeLimit(52428800)]public async Task<IActionResult> Photos(string token,[FromForm]List<IFormFile> files,[FromForm]PhotoCategory category=PhotoCategory.Other){var j=await Find(token);if(j is null)return NotFound();var result=new List<JobPhoto>();foreach(var f in files)result.Add(await storage.SaveAsync(j.Id,f,category,true,null));return Ok(result);} }

[ApiController,Route("api/photos"),Authorize] public class PhotosController(AppDbContext db,IFileStorage storage):ControllerBase {
 [HttpGet]public async Task<IActionResult>Get([FromQuery]string? q,[FromQuery]PhotoCategory? category,[FromQuery]int page=1,[FromQuery]int pageSize=60){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,200);var photos=db.JobPhotos.AsNoTracking().Include(x=>x.Job).ThenInclude(x=>x.Patient).Include(x=>x.Job).ThenInclude(x=>x.Clinic).AsQueryable();if(category.HasValue)photos=photos.Where(x=>x.Category==category);if(!string.IsNullOrWhiteSpace(q))photos=photos.Where(x=>x.Job.JobCode.Contains(q)||x.Job.Patient.PatientCode.Contains(q)||x.Job.Patient.FirstName.Contains(q)||x.Job.Patient.LastName.Contains(q)||x.Job.Clinic.Name.Contains(q));var total=await photos.CountAsync();Response.Headers.Append("X-Total-Count",total.ToString());return Ok(await photos.OrderByDescending(x=>x.UploadedAt).Skip((page-1)*pageSize).Take(pageSize).Select(x=>new{x.Id,x.JobId,x.Category,x.OriginalFileName,x.StoredFileName,x.ThumbnailStoredFileName,x.MimeType,x.FileSize,x.UploadedViaQr,x.UploadedAt,x.Job.JobCode,PatientCode=x.Job.Patient.PatientCode,PatientName=x.Job.Patient.FirstName+" "+x.Job.Patient.LastName,ClinicName=x.Job.Clinic.Name}).ToListAsync());}
 [HttpPatch("{id:int}/category"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Category(int id,PhotoCategoryDto d){var photo=await db.JobPhotos.FindAsync(id);if(photo is null)return NotFound();photo.Category=d.Category;await db.SaveChangesAsync();return Ok(new{photo.Id,photo.Category});}
 [HttpDelete("{id:int}"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Delete(int id){var photo=await db.JobPhotos.FindAsync(id);if(photo is null)return NotFound();await storage.DeleteAsync(photo);db.JobPhotos.Remove(photo);await db.SaveChangesAsync();return NoContent();}
}

[ApiController,Route("api/settings"),Authorize(Roles="Admin")] public class SettingsController(AppDbContext db,IWindowsPrinterService printers):ControllerBase {
 [HttpGet]public Task<List<SystemSetting>>Get()=>db.SystemSettings.ToListAsync();
 [HttpGet("printers")]public IActionResult Printers()=>Ok(printers.GetInstalledPrinters());
 [HttpPut("{key}")]public async Task<IActionResult>Put(string key,SettingDto d){var x=await db.SystemSettings.SingleOrDefaultAsync(s=>s.Key==key);if(x is null){x=new(){Key=key,Value=d.Value};db.Add(x);}else x.Value=d.Value;await db.SaveChangesAsync();return Ok(x);}
 [HttpPost("backup")]public async Task<IActionResult>Backup(){var dataRoot=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"OpenDentalFlow");var backupDir=Path.Combine(dataRoot,"backups");Directory.CreateDirectory(backupDir);var stamp=DateTime.Now.ToString("yyyyMMdd-HHmmss");var snapshot=Path.Combine(backupDir,$"database-{stamp}.db");var zipPath=Path.Combine(backupDir,$"OpenDentalLab-backup-{stamp}.zip");try{var source=(Microsoft.Data.Sqlite.SqliteConnection)db.Database.GetDbConnection();if(source.State!=System.Data.ConnectionState.Open)await source.OpenAsync();await using(var destination=new Microsoft.Data.Sqlite.SqliteConnection($"Data Source={snapshot};Pooling=False")){await destination.OpenAsync();source.BackupDatabase(destination);await destination.CloseAsync();}using(var archive=System.IO.Compression.ZipFile.Open(zipPath,System.IO.Compression.ZipArchiveMode.Create)){archive.CreateEntryFromFile(snapshot,"opendentalflow.db",System.IO.Compression.CompressionLevel.Optimal);var uploads=Path.Combine(dataRoot,"uploads");if(Directory.Exists(uploads))foreach(var file in Directory.EnumerateFiles(uploads,"*",SearchOption.AllDirectories))archive.CreateEntryFromFile(file,Path.Combine("uploads",Path.GetRelativePath(uploads,file)).Replace('\\','/'),System.IO.Compression.CompressionLevel.Fastest);}return Ok(new{message="Yedek oluşturuldu.",fileName=Path.GetFileName(zipPath),folder=backupDir});}finally{Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();if(System.IO.File.Exists(snapshot))System.IO.File.Delete(snapshot);}}
}
[ApiController,Route("api/users"),Authorize(Roles="Admin")] public class UsersController(AppDbContext db):ControllerBase {
 [HttpGet]public async Task<IActionResult>Get()=>Ok(await db.Users.AsNoTracking().OrderBy(x=>x.Username).Select(x=>new{x.Id,x.Username,x.Role,x.IsActive,x.CreatedAt}).ToListAsync());
 [HttpPost]public async Task<IActionResult>Create(CreateUserDto d){var username=d.Username.Trim();if(await db.Users.AnyAsync(x=>x.Username.ToLower()==username.ToLower()))return Conflict(new{message="Bu kullanıcı adı zaten kullanılıyor."});var x=new User{Username=username,PasswordHash=BCrypt.Net.BCrypt.HashPassword(d.Password),Role=d.Role,IsActive=d.IsActive};db.Users.Add(x);await db.SaveChangesAsync();return CreatedAtAction(nameof(Get),new{id=x.Id},new{x.Id,x.Username,x.Role,x.IsActive,x.CreatedAt});}
 [HttpPut("{id:int}")]public async Task<IActionResult>Update(int id,UpdateUserDto d){var x=await db.Users.FindAsync(id);if(x is null)return NotFound();var currentId=int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var uid)?uid:0;if(id==currentId&&(!d.IsActive||d.Role!=UserRole.Admin))return BadRequest(new{message="Kendi yönetici hesabınızı pasif yapamaz veya yetkisini düşüremezsiniz."});var username=d.Username.Trim();if(await db.Users.AnyAsync(u=>u.Id!=id&&u.Username.ToLower()==username.ToLower()))return Conflict(new{message="Bu kullanıcı adı zaten kullanılıyor."});x.Username=username;x.Role=d.Role;x.IsActive=d.IsActive;if(!string.IsNullOrWhiteSpace(d.Password))x.PasswordHash=BCrypt.Net.BCrypt.HashPassword(d.Password);await db.SaveChangesAsync();return Ok(new{x.Id,x.Username,x.Role,x.IsActive,x.CreatedAt});}
}
[ApiController,Route("api/job-types"),Authorize] public class JobTypesController(AppDbContext db):ControllerBase { [HttpGet]public Task<List<JobTypeDefinition>>Get()=>db.JobTypes.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Name).ToListAsync(); [HttpPost,Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Create(JobTypeDto d){var x=new JobTypeDefinition{Name=d.Name.Trim(),DefaultMaterial=d.DefaultMaterial?.Trim(),IsActive=d.IsActive,SortOrder=d.SortOrder};db.Add(x);try{await db.SaveChangesAsync();}catch(DbUpdateException){return Conflict(new{message="Bu iş türü zaten tanımlı."});}return Ok(x);} [HttpPut("{id:int}"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Update(int id,JobTypeDto d){var x=await db.JobTypes.FindAsync(id);if(x is null)return NotFound();x.Name=d.Name.Trim();x.DefaultMaterial=d.DefaultMaterial?.Trim();x.IsActive=d.IsActive;x.SortOrder=d.SortOrder;await db.SaveChangesAsync();return Ok(x);} [HttpDelete("{id:int}"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Delete(int id){var x=await db.JobTypes.FindAsync(id);if(x is null)return NotFound();x.IsActive=false;await db.SaveChangesAsync();return NoContent();} }
[ApiController,Route("api/materials"),Authorize] public class MaterialsController(AppDbContext db):ControllerBase { [HttpGet]public Task<List<MaterialDefinition>>Get()=>db.Materials.AsNoTracking().Where(x=>x.IsActive).OrderBy(x=>x.SortOrder).ThenBy(x=>x.Name).ToListAsync(); [HttpPost,Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Create(MaterialDto d){var x=new MaterialDefinition{Name=d.Name.Trim(),IsActive=d.IsActive,SortOrder=d.SortOrder};db.Add(x);try{await db.SaveChangesAsync();}catch(DbUpdateException){return Conflict(new{message="Bu materyal zaten tanımlı."});}return Ok(x);} [HttpPut("{id:int}"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Update(int id,MaterialDto d){var x=await db.Materials.FindAsync(id);if(x is null)return NotFound();x.Name=d.Name.Trim();x.IsActive=d.IsActive;x.SortOrder=d.SortOrder;await db.SaveChangesAsync();return Ok(x);} [HttpDelete("{id:int}"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult>Delete(int id){var x=await db.Materials.FindAsync(id);if(x is null)return NotFound();x.IsActive=false;await db.SaveChangesAsync();return NoContent();} }
