using System.IdentityModel.Tokens.Jwt; using System.Security.Claims; using System.Text; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using Microsoft.IdentityModel.Tokens; using OpenDentalFlow.Api.Contracts; using OpenDentalFlow.Api.Data; using OpenDentalFlow.Api.Domain; using OpenDentalFlow.Api.Services;
namespace OpenDentalFlow.Api.Controllers;

[ApiController,Route("api/auth")] public class AuthController(AppDbContext db,IConfiguration cfg):ControllerBase { [HttpPost("login"),AllowAnonymous] public async Task<IActionResult> Login(LoginDto dto){var u=await db.Users.SingleOrDefaultAsync(x=>x.Username==dto.Username&&x.IsActive); if(u is null||!BCrypt.Net.BCrypt.Verify(dto.Password,u.PasswordHash))return Unauthorized(new{message="Kullanıcı adı veya parola hatalı."}); var key=new SymmetricSecurityKey(Encoding.UTF8.GetBytes(cfg["Jwt:Key"]!)); var token=new JwtSecurityToken(claims:[new(ClaimTypes.NameIdentifier,u.Id.ToString()),new(ClaimTypes.Name,u.Username),new(ClaimTypes.Role,u.Role.ToString())],expires:DateTime.UtcNow.AddHours(12),signingCredentials:new(key,SecurityAlgorithms.HmacSha256));return Ok(new{token=new JwtSecurityTokenHandler().WriteToken(token),u.Username,role=u.Role.ToString()});} }

[ApiController,Route("api/clinics"),Authorize] public class ClinicsController(AppDbContext db,IShortCodeService codes):ControllerBase { [HttpGet] public Task<List<Clinic>> Get()=>db.Clinics.OrderBy(x=>x.Name).ToListAsync(); [HttpGet("suggestions")] public Task<List<string>> Suggestions([FromQuery]string name)=>codes.SuggestAsync(name); [HttpPost,Authorize(Roles="Admin,Employee")] public async Task<IActionResult> Create(ClinicDto d){var x=new Clinic{Name=d.Name.Trim(),ShortCode=d.ShortCode.ToUpperInvariant(),Phone=d.Phone,Address=d.Address,IsActive=d.IsActive};db.Add(x);try{await db.SaveChangesAsync();}catch(DbUpdateException){return Conflict(new{message="Klinik kısa kodu kullanımda."});}return CreatedAtAction(nameof(Get),new{id=x.Id},x);} [HttpPut("{id:int}"),Authorize(Roles="Admin,Employee")] public async Task<IActionResult> Update(int id,ClinicDto d){var x=await db.Clinics.FindAsync(id);if(x is null)return NotFound();x.Name=d.Name;x.ShortCode=d.ShortCode.ToUpperInvariant();x.Phone=d.Phone;x.Address=d.Address;x.IsActive=d.IsActive;await db.SaveChangesAsync();return Ok(x);} }

[ApiController,Route("api/patients"),Authorize] public class PatientsController(AppDbContext db):ControllerBase { [HttpGet] public async Task<IActionResult> Get([FromQuery]string? q){var x=db.Patients.Include(p=>p.Clinic).AsQueryable();if(!string.IsNullOrWhiteSpace(q))x=x.Where(p=>p.PatientCode.Contains(q)||p.FirstName.Contains(q)||p.LastName.Contains(q)||p.Clinic.Name.Contains(q));return Ok(await x.OrderByDescending(p=>p.CreatedAt).ToListAsync());} [HttpGet("{id:int}")]public async Task<IActionResult> One(int id){var x=await db.Patients.Include(p=>p.Clinic).Include(p=>p.Jobs).SingleOrDefaultAsync(p=>p.Id==id);return x is null?NotFound():Ok(x);} }

[ApiController,Route("api/jobs"),Authorize] public class JobsController(AppDbContext db,ICodeService codes,IFileStorage storage,IConfiguration cfg,ILabelService labels):ControllerBase {
 IQueryable<Job> Full()=>db.Jobs.Include(x=>x.Patient).Include(x=>x.Clinic).Include(x=>x.Photos).Include(x=>x.Notes).Include(x=>x.StatusHistory);
 [HttpGet] public async Task<IActionResult> Get([FromQuery]string? q,[FromQuery]JobStatus? status){var x=Full();if(status.HasValue)x=x.Where(j=>j.Status==status);if(!string.IsNullOrWhiteSpace(q))x=x.Where(j=>j.JobCode.Contains(q)||j.Patient.PatientCode.Contains(q)||j.Patient.FirstName.Contains(q)||j.Patient.LastName.Contains(q)||j.Clinic.Name.Contains(q)||j.Clinic.ShortCode.Contains(q));return Ok(await x.OrderByDescending(j=>j.CreatedAt).ToListAsync());}
 [HttpGet("{id:int}")]public async Task<IActionResult> One(int id){var x=await Full().SingleOrDefaultAsync(j=>j.Id==id);return x is null?NotFound():Ok(x);} [HttpGet("code/{jobCode}")]public async Task<IActionResult> ByCode(string jobCode){var x=await Full().SingleOrDefaultAsync(j=>j.JobCode==jobCode);return x is null?NotFound():Ok(x);}
 [HttpPost,Authorize(Roles="Admin,Employee")] public async Task<IActionResult> Create(CreateJobDto d){if(d.Teeth.Any(t=>t is <11 or >48))return BadRequest(new{message="Geçersiz FDI diş numarası."}); await using var tx=await db.Database.BeginTransactionAsync(System.Data.IsolationLevel.Serializable);var clinic=await db.Clinics.SingleOrDefaultAsync(x=>x.Id==d.ClinicId&&x.IsActive);if(clinic is null)return BadRequest(new{message="Aktif klinik seçin."});Patient? p=d.PatientId is null?null:await db.Patients.SingleOrDefaultAsync(x=>x.Id==d.PatientId&&x.ClinicId==d.ClinicId);if(p is null){if(string.IsNullOrWhiteSpace(d.FirstName)||string.IsNullOrWhiteSpace(d.LastName))return BadRequest(new{message="Yeni hasta için ad ve soyad zorunludur."});clinic.LastPatientSequence++;p=new Patient{Clinic=clinic,ClinicSequence=clinic.LastPatientSequence,PatientCode=$"{clinic.ShortCode}-{clinic.LastPatientSequence:000}",FirstName=d.FirstName.Trim(),LastName=d.LastName.Trim(),Description=d.PatientDescription};db.Patients.Add(p);await db.SaveChangesAsync();}var seq=await db.Jobs.Where(x=>x.PatientId==p.Id).MaxAsync(x=>(int?)x.JobSequence)??0;seq++;var j=new Job{Patient=p,Clinic=clinic,JobSequence=seq,JobCode=$"{p.PatientCode}-{seq}",DueDate=d.DueDate,JobType=d.JobType,Material=d.Material,Shade=d.Shade,Teeth=string.Join(',',d.Teeth.Distinct().Order()),UnitCount=d.UnitCount??d.Teeth.Distinct().Count(),Priority=d.Priority,Description=d.Description,AccessToken=codes.Token()};db.Jobs.Add(j);db.JobStatusHistory.Add(new(){Job=j,OldStatus=JobStatus.Registered,NewStatus=JobStatus.Registered});try{await db.SaveChangesAsync();await tx.CommitAsync();}catch(DbUpdateException){await tx.RollbackAsync();return Conflict(new{message="Eş zamanlı kod üretimi çakıştı; yeniden deneyin."});}return CreatedAtAction(nameof(One),new{id=j.Id},new{j.Id,j.JobCode,j.AccessToken});}
 [HttpPatch("{id:int}/status"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult> Status(int id,StatusDto d){var j=await db.Jobs.FindAsync(id);if(j is null)return NotFound();var old=j.Status;j.Status=d.Status;j.UpdatedAt=DateTime.UtcNow;if(d.Status is JobStatus.Ready or JobStatus.Delivered)j.CompletedAt??=DateTime.UtcNow;db.JobStatusHistory.Add(new(){JobId=id,OldStatus=old,NewStatus=d.Status,ChangedByUserId=UserId()});await db.SaveChangesAsync();return Ok(j);}
 [HttpPost("{id:int}/notes"),Authorize(Roles="Admin,Employee")]public async Task<IActionResult> Note(int id,NoteDto d){if(!await db.Jobs.AnyAsync(x=>x.Id==id))return NotFound();var n=new JobNote{JobId=id,Text=d.Text,CreatedByUserId=UserId()};db.Add(n);await db.SaveChangesAsync();return Ok(n);} [HttpPost("{id:int}/photos"),Authorize(Roles="Admin,Employee"),RequestSizeLimit(52428800)]public async Task<IActionResult> Photos(int id,[FromForm]List<IFormFile> files,[FromForm]PhotoCategory category=PhotoCategory.Other){if(!await db.Jobs.AnyAsync(x=>x.Id==id))return NotFound();var result=new List<JobPhoto>();foreach(var f in files)result.Add(await storage.SaveAsync(id,f,category,false,UserId()));return Ok(result);}
 [HttpPost("{id:int}/regenerate-access-token"),Authorize(Roles="Admin")]public async Task<IActionResult> Regen(int id){var j=await db.Jobs.FindAsync(id);if(j is null)return NotFound();j.AccessToken=codes.Token();j.AccessEnabled=true;await db.SaveChangesAsync();return Ok(new{j.AccessToken});}
 [HttpGet("{id:int}/label")]public async Task<IActionResult> Label(int id){var j=await Full().SingleOrDefaultAsync(x=>x.Id==id);if(j is null)return NotFound();var url=$"{cfg["PublicBaseUrl"]}/j/{j.AccessToken}";return Ok(new{job=j,publicUrl=url,qr=$"/api/jobs/{id}/label/qr",barcode=$"/api/jobs/{id}/label/barcode"});} [HttpGet("{id:int}/label/qr")]public async Task<IActionResult> Qr(int id){var j=await db.Jobs.FindAsync(id);return j is null?NotFound():File(labels.Qr($"{cfg["PublicBaseUrl"]}/j/{j.AccessToken}"),"image/png");}[HttpGet("{id:int}/label/barcode")]public async Task<IActionResult> Barcode(int id){var j=await db.Jobs.FindAsync(id);return j is null?NotFound():File(labels.Barcode(j.JobCode),"image/png");} int? UserId()=>int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:null;
}

[ApiController,Route("api/public/jobs"),AllowAnonymous] public class PublicJobsController(AppDbContext db,IFileStorage storage):ControllerBase { async Task<Job?> Find(string token)=>await db.Jobs.Include(x=>x.Patient).Include(x=>x.Clinic).Include(x=>x.Photos).Include(x=>x.Notes).SingleOrDefaultAsync(x=>x.AccessToken==token&&x.AccessEnabled); [HttpGet("{token}")]public async Task<IActionResult> Get(string token){var j=await Find(token);return j is null?NotFound(new{message="Bağlantı geçersiz veya iptal edilmiş."}):Ok(j);} [HttpPost("{token}/notes")]public async Task<IActionResult> Note(string token,NoteDto d){var j=await Find(token);if(j is null)return NotFound();var n=new JobNote{JobId=j.Id,Text=d.Text,CreatedViaQr=true};db.Add(n);await db.SaveChangesAsync();return Ok(n);} [HttpPost("{token}/photos"),RequestSizeLimit(52428800)]public async Task<IActionResult> Photos(string token,[FromForm]List<IFormFile> files,[FromForm]PhotoCategory category=PhotoCategory.Other){var j=await Find(token);if(j is null)return NotFound();var result=new List<JobPhoto>();foreach(var f in files)result.Add(await storage.SaveAsync(j.Id,f,category,true,null));return Ok(result);} }

[ApiController,Route("api/settings"),Authorize(Roles="Admin")] public class SettingsController(AppDbContext db):ControllerBase { [HttpGet]public Task<List<SystemSetting>>Get()=>db.SystemSettings.ToListAsync();[HttpPut("{key}")]public async Task<IActionResult>Put(string key,SettingDto d){var x=await db.SystemSettings.SingleOrDefaultAsync(s=>s.Key==key);if(x is null){x=new(){Key=key,Value=d.Value};db.Add(x);}else x.Value=d.Value;await db.SaveChangesAsync();return Ok(x);} }
[ApiController,Route("api/users"),Authorize(Roles="Admin")] public class UsersController(AppDbContext db):ControllerBase { [HttpGet]public async Task<IActionResult>Get()=>Ok(await db.Users.Select(x=>new{x.Id,x.Username,x.Role,x.IsActive,x.CreatedAt}).ToListAsync()); }
