using System.ComponentModel.DataAnnotations;
using OpenDentalFlow.Api.Domain;
namespace OpenDentalFlow.Api.Contracts;
public record LoginDto([Required]string Username,[Required]string Password);
public record ClinicDto([Required]string Name,string? ShortCode,string? Phone,string? Address,string? Notes,bool IsActive=true);
public record CreateJobDto(int ClinicId,int? PatientId,string? FirstName,string? LastName,string? PatientDescription,DateTime? DueDate,[Required]string JobType,string? Material,string? Shade,List<int> Teeth,int? UnitCount,bool DigitalModelRequired=false,string Priority="Normal",string? Description=null);
public record JobTypeDto([Required,MaxLength(100)]string Name,[MaxLength(100)]string? DefaultMaterial,bool IsActive=true,int SortOrder=0);
public record MaterialDto([Required,MaxLength(100)]string Name,bool IsActive=true,int SortOrder=0);
public record CreateUserDto([Required,MinLength(3),MaxLength(50)]string Username,[Required,MinLength(8),MaxLength(100)]string Password,UserRole Role=UserRole.Employee,bool IsActive=true);
public record UpdateUserDto([Required,MinLength(3),MaxLength(50)]string Username,[MinLength(8),MaxLength(100)]string? Password,UserRole Role,bool IsActive=true);
public record StatusDto(JobStatus Status);
public record NoteDto([Required,MaxLength(2000)]string Text);
public record ActivityDto([Required,MaxLength(80)]string StepType,[MaxLength(1000)]string? Description);
public record PhotoCategoryDto(PhotoCategory Category);
public record AccessDto(bool Enabled);
public record SettingDto([Required]string Value);
